# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [20]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np

# Let's define a one-dimensional array 
list_1=[50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [21]:
# Let's create a numpy array from the list "my_list"

my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [22]:
type(my_numpy_array)

numpy.ndarray

In [23]:
# Multi-dimensional (Matrix definition) 
my_matrix=np.array([[2, 5, 8],[7, 3, 6] ])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [24]:
mini=np.array([[3, 7 , 9, 3],[4, 3, 2, 2]])
mini

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [25]:
# "rand()" uniform distribution between 0 and 1
import random
x =np.random.rand(20)
x

array([0.01769682, 0.00373158, 0.02991919, 0.37018522, 0.64310787,
       0.29960717, 0.23843093, 0.18010939, 0.78207765, 0.67439259,
       0.31010507, 0.04282706, 0.11730768, 0.0425635 , 0.57626287,
       0.53912276, 0.51875914, 0.21593543, 0.56287894, 0.06339889])

In [26]:
# you can create a matrix of random number as well
x=np.random.rand(3,3)
x

array([[0.56741959, 0.2998447 , 0.80793627],
       [0.595066  , 0.85200537, 0.2185036 ],
       [0.5093113 , 0.98886598, 0.46810781]])

In [27]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,50)
x

33

In [28]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(1,100,15)
x

array([ 9, 63, 82, 52,  7, 20, 38, 56, 45, 21, 18, 11, 20, 69,  2])

In [29]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
# create a diagonal of ones and zeros everywhere else
x=np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [31]:
# Matrix of ones
x=np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [32]:
# Array of zeros
x=np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [33]:
x=int(input("Enter Number"))
z=np.random.randint(0,x,10)
z

array([1, 3, 1, 5, 3, 5, 4, 4, 5, 4])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [34]:
# np.arange() returns an evenly spaced values within a given interval


In [35]:
x=np.arange(1,10)
x



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Add 2 numpy arrays together


In [37]:
y=np.arange(1,10)
sum=x+y
sum


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [38]:
X=np.array([5,7,20])
Y=np.array([9,15,4])
dis=Y-X
dis

array([  4,   8, -16])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [39]:
import numpy as np
my_numpy_array=np.array([3,5,6,2,8,10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [40]:
# Access specific index from the numpy array
my_numpy_array[3]

2

In [41]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3]

array([3, 5, 6])

In [42]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4]=7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [43]:
# Let's define a two dimensional numpy array
matrix=np.random.randint(1,10,(4,4))
matrix

array([[4, 4, 1, 1],
       [2, 2, 5, 5],
       [1, 9, 1, 5],
       [9, 1, 3, 6]])

In [44]:
# Get a row from a mtrix
matrix[0]


array([4, 4, 1, 1])

In [45]:
# Get one element
matrix[0][2]

1

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [46]:
x =np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

x[4]=0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [47]:
m=np.random.randint(1,10,(5,5))
m

array([[7, 7, 7, 1, 2],
       [7, 6, 3, 1, 3],
       [2, 1, 5, 9, 1],
       [3, 2, 1, 9, 7],
       [7, 7, 7, 2, 4]])

In [48]:
new=m[m>7]
new

array([9, 9])

In [49]:
# Obtain odd elements only
news=m[m % 2==0]
news

array([2, 6, 2, 2, 2, 4])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [50]:
x =np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

x[x < 0] = 0
x[x %2==1]= -2
x


array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [51]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [52]:
import pandas as pd


In [53]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank=pd.DataFrame({'Bank Client Id':[111,222,333,444],
                 'Bank Client Name':['steven','sean','nick','dee'],
                 'Net Worth [$]':[3500,29000,10000,2000],
                 'Years With Bank':[3,4,9,5]      })
bank

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
0             111           steven           3500                3
1             222             sean          29000                4
2             333             nick          10000                9
3             444              dee           2000                5

In [54]:
# Let's obtain the data type 
type(bank)

pandas.core.frame.DataFrame

In [55]:
# you can only view the first couple of rows using .head()
bank.head(2)

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
0             111           steven           3500                3
1             222             sean          29000                4

In [56]:
# you can only view the last couple of rows using .tail()
bank.tail(2)


Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
2             333             nick          10000                9
3             444              dee           2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [57]:
portfolio_df=pd.DataFrame({'Ticker/Comapny':['AAPL','FZROX','FXAIX'],
                          'Number of Shares':[10, 20, 30],
                           'Price Per Share':[166.17, 14.32, 143.10],
                          })
value=portfolio_df['Price Per Share']*portfolio_df['Number of Shares']
value.sum()

6241.1

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [58]:
# Pandas is used to read a csv file and store data in a DataFrame
import pandas as pd
house_price = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

ImportError: lxml not found, please install it

In [ ]:
!pip install lxml
!python -m pip install --upgrade pip

In [ ]:
# Read tabular data using read_html
import pandas as pd
house_price = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')


URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1045)>

In [ ]:
!pip install lxml

In [ ]:
!python -m pip install --upgrade pip

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
import pandas as pd
retire=pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retire

[                                        Year of birth  \
 0                                      1937 and prior   
 1                                                1938   
 2                                                1939   
 3                                                1940   
 4                                                1941   
 5                                                1942   
 6                                             1943-54   
 7                                                1955   
 8                                                1956   
 9                                                1957   
 10                                               1958   
 11                                               1959   
 12                                     1960 and later   
 13  Notes: 1. Persons born on January 1 of any yea...   
 
                                                   Age  
 0                                                  65  
 1            

# TASK #8: PANDAS OPERATIONS

In [ ]:
# Let's define a dataframe as follows:
bank=pd.DataFrame({'Bank Client Id':[111,222,333,444],
                 'Bank Client Name':['Steven','Sean','Nick','Dee'],
                 'Net Worth [$]':[3500,29000,10000,2000],
                 'Years With Bank':[3,4,9,5]      })
bank

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
0             111           Steven           3500                3
1             222             Sean          29000                4
2             333             Nick          10000                9
3             444              Dee           2000                5

In [ ]:
# Pick certain rows that satisfy a certain criteria 
loyal=bank[bank['Years With Bank']>=5]
loyal

Bank Client Id Bank Client Name  Net Worth [$]  Years With Bank
2             333             Nick          10000                9
3             444              Dee           2000                5

In [ ]:
# Delete a column from a DataFrame


MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
net=bank[bank['Net Worth [$]'] >= 5000]
net['Net Worth [$]'].sum()


39000

# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [ ]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [ ]:
bank_client_df

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def update_worth(balance):
    balance = balance * 3 + 200
    return balance
result = bank_client_df['Net worth [$]'].apply(update_worth)
result.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True


In [ ]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by= 'Years with bank',inplace = True)


In [ ]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [ ]:
import pandas as pd
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'C':['C0','C1','C2','C3'],
                  'D':['D0','D1','D2','D3']},
                index = [0, 1, 2, 3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B6','B7'],
                  'C':['C4','C5','C6','C7'],
                  'D':['D4','D5','D6','D7']},
                index = [4, 5, 6, 7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B':['B8','B9','B10','B11'],
                  'C':['C8','C9','C10','C11'],
                  'D':['D8','D9','D10','D11']},
                index = [8, 9, 10, 11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [62]:
import pandas as pd

bank_df1=pd.DataFrame({ 'Client ID':[1, 2, 3, 4, 5] , 
                        'First Name':['Joneth','Nathan','Jeremiah','Ricky','Kane'],
                        'Last Name':['D','T','T','P','P'],  
                       })
bank_df2=pd.DataFrame({ 'Client ID':[6, 7, 8, 9, 10], 
                        'First Name':['Linda','Cherry','Emily','Zack','Joe'],
                      'Last Name':['P','K','L','K','K'],
                      })
client_salary=pd.DataFrame({'Client ID':[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                            "Annual Salary":[90000, 80000, 125000, 10000, 90000, 80000, 75000, 85000, 50000, 70000]
    
})
bank_all = pd.concat([bank_df1,bank_df2])
bank_all=pd.merge(bank_all, client_salary, on = "Client ID")
bank_all

new_client={'Client ID':[11],
           'First Name': ['Terry'],
           'Last Name': ['S'],
           'Annual Salary':[145000]}
new_clientdf=pd.DataFrame(new_client, columns = ['Client ID','First Name','Last Name','Annual Salary'])
new_df=pd.concat([bank_all,new_clientdf], axis = 0)
new_df

Client ID First Name Last Name  Annual Salary
0          1     Joneth         D          90000
1          2     Nathan         T          80000
2          3   Jeremiah         T         125000
3          4      Ricky         P          10000
4          5       Kane         P          90000
5          6      Linda         P          80000
6          7     Cherry         K          75000
7          8      Emily         L          85000
8          9       Zack         K          50000
9         10        Joe         K          70000
0         11      Terry         S         145000

# EXCELLENT JOB!